leafo/scssphp

src/Server.php

Without the return, the server renders a 304 Not Modified if there's an error

Fix the return value in case of a parse error

---

src/Server.php

In most cases the browser’s ETAG will be the same with one in the meta
file, event if the files are changed in the mean while, thus it will
always return a 302

[ ETAG ] Don't compare meta-etag with browser etag

---

scss.inc.php

I ran into an issue when including `scss.inc.php` where a silly autoloader started logging errors about missing the file `Scssc.php`. A little bit unsure about the reason for `class_exists` but I assume it should be safe to ignore calling autoloaders here.

Don't call autoloader when checking if class exists

---

src/Compiler.php
src/Server.php

quick check to needsCompile for changed registeredVars with a crc32 hash
a simple implementation of a check if it needs to compile new if the registeredVars have changed, maybe if they are from a DB

crc32 needsCompile check for serialized registeredVars 

---

src/Colors.php

It is supported by all current major browsers.
Some details:
* https://drafts.csswg.org/css-color/#valdef-color-rebeccapurple
* http://codepen.io/trezy/post/honoring-a-great-man

Added `rebeccapurple` named color

---

src/Compiler.php
tests/inputs/builtins.scss
tests/outputs/builtins.css
tests/outputs_numbered/builtins.css

I ran into an odd scenario with my company's codebase when I upgraded from 0.3.3 to 0.6.2. I haven't followed all of the logic that's happening to actually populate variables, but from using xdebug, it seems like a variable's unit doesn't does not always get unset, but instead set to `false` or `0`.
I included an update to the unit tests for this scenario, but I'll include it here, too. It's a vastly simplified version of what is breaking in our code.
```
$test: 50%; 
$test: 0 + ($test / 100%); // Adding zero coerces to a number, might not be necessary
color: percentage($test);
// Expected result: 50%
// Actual result: 0.5%
```
There might be a better solution to this, but this is what is working for me.

Only divide by 100 if number is truly a percent

---

src/Compiler.php
tests/inputs/operators.scss
tests/outputs/operators.css
tests/outputs_numbered/operators.css

Example:
` $a: (null or 'foo');  // $a evaluates NULL, and it shoud be 'foo'`

Fix: "or" and "and" operators evaluates NULL as TRUE value.

---

src/Compiler.php
tests/inputs/functions.scss
tests/inputs/mixins.scss
tests/outputs/functions.css
tests/outputs/mixins.css
tests/outputs_numbered/functions.css
tests/outputs_numbered/mixins.css

@robocoder 
Fixes mixin and variable scopes, adds unit tests to detect the broken behavior.

Fix mixin and variable scopes (#440)

---

src/Compiler.php

When a null value is given to coerceValue the following error is returned:
~~~
_WARNING [2]: preg_match() expects parameter 2 to be string, array given
/vendor/leafo/scssphp/src/Compiler.php, line: 3635
~~~
This change fixes that for me.

Preg_match error array > string

---

src/Compiler.php
tests/inputs/extends.scss
tests/inputs/extends_nesting.scss
tests/inputs/nested_mixins.scss
tests/outputs/extends.css
tests/outputs/extends_nesting.css
tests/outputs/nested_mixins.css
tests/outputs_numbered/extends.css
tests/outputs_numbered/extends_nesting.css
tests/outputs_numbered/nested_mixins.css

I noticed during work that the bit added to the test case was not compiled the same using `node-sass`. It may look strange that the build files are changed but I've confirmed that the output of `extends.css` matches 1 to 1 the compiled version of `extends.scss` using `node-sass`.
```
$ git log -1 --oneline && node-sass -v && vendor/bin/phpunit 
98ae18f Extend resolution was generating invalid selectors
node-sass	3.8.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
PHPUnit 3.7.38 by Sebastian Bergmann.
Configuration read from /home/fred/apps/scssphp/phpunit.xml.dist
.................S.............................................  63 / 349 ( 18%)
........................S...................................... 126 / 349 ( 36%) …
```

Extend resolution was generating invalid selectors

---

src/Compiler.php
tests/inputs/content.scss
tests/outputs/content.css
tests/outputs_numbered/content.css

Before the following scss would work fine with ruby sass, but throw an "Expected @content inside of mixin" exception in pscss.
````
@mixin border-radius($radius) {
-webkit-border-radius: $radius;
-moz-border-radius: $radius;
-ms-border-radius: $radius;
border-radius: $radius;
@content;
}
a {
background: red;
padding: 10px;
@include border-radius(10px);
}
```
This allows it to work.

Let @content work when a block isn’t passed in.

---

src/Node/Number.php

Function each() deprecated in PHP7.2

fixes #532 Substitute deprecated php function each()

---

src/Block.php
src/Compiler.php
src/Formatter.php
src/Formatter/Compressed.php
src/Formatter/Crunched.php
src/Formatter/Debug.php
src/Formatter/Expanded.php
src/Formatter/Nested.php
src/Formatter/OutputBlock.php
src/Parser.php
src/SourceMap/Base64VLQEncoder.php
src/SourceMap/SourceMapGenerator.php

* Add setSourceMap() and setSourceMapOptions() methods.
* Modify Parser, InputBlock and and Block to keep track of the original source file, line and and column.
* Add SourceMapGenerator, hugely copied from oyekorge/less.php
* Modify formatters to keep track of the current position, and to call SourceMapGenerator::addMapping when needed.
* add sourceMap inlining to Compiler

See #135: add inline sourceMaps support

---

example/Server.php
scss.inc.php
src/Compiler.php
src/SourceMap/SourceMapGenerator.php

Taking code from less.php, this allows for SOURCE_MAP_FILE sourceMap type to output file based source maps instead of only inline source maps being included in the css file output. Also includes a modified version of the cachedCompile() method into the Server example.

Adds file based source maps in addition to inline source maps; adds cachedCompile() to Server

---

src/Compiler.php

This allows passing an object of a custom SourceMapGenerator (must be extended from SourceMapGenerator()). as a type of sourcemap.

Add option to pass a custom SourceMapGenerator object

---

src/Compiler.php
tests/inputs/map.scss
tests/outputs/map.css
tests/outputs_numbered/map.css

`libMapMerge` used to just concatenate maps, i.e. two maps containing the same key would be merged into one map containing that key twice. The duplicate key did not appear in the css output when the map was used directly in then scss, but it was used by `each` loops.
This patch fixes it so that the resulting map contains that key only once.

Actually merge maps instead of just concatenating

---

src/Compiler.php

Hi,
First of all, thank you for this incredible package !
I've been working on PHP Code Quality tool called phpstan, and here is a small enhancement inside comments of the `Compiler::addImportPath` function which should also allow `callable` type in input.
Unless, you get an error when launching phpstan : 
```
------ ---------------------------------------------------------------------- 
Line   src/Services/WhiteLabelService.php                                    
------ ---------------------------------------------------------------------- 
18     Parameter #1 $path of method Leafo\ScssPhp\Compiler::addImportPath()  
expects string, Closure given.                                        
------ ----------------------------------------------------------------------
```

fix doc for addImportPath, should also accept callable as input

---

.gitignore
src/SourceMap/SourceMapGenerator.php

If sourceMapBasepath is empty the function strpos() throws a needle empty error. This is a very small bug fix which checks the length of the sourceMapBasepath before strpos() is called.

Bug fix error thrown from strpos if needle (basePath) is empty

---

tests/ScssTest.php

"continue statements targeting switch control flow structures will now generate a warning. In PHP such continue statements are equivalent to break, while they behave as continue 2 in other languages."
http://php.net/manual/en/migration73.incompatible.php
"In PHP the switch statement is considered a looping structure for the purposes of continue. continue behaves like break (when no arguments are passed). If a switch is inside a loop, continue 2 will continue with the next iteration of the outer loop."
http://php.net/manual/en/control-structures.continue.php
Signed-off-by: Vince <git@darkain.com>

Fix for "continue" causing a warning in PHP 7.3

---

src/Compiler.php

Change private properties to protected in compiler class.
If Compiler class is extended, currently its impossible to access some methods and variables in child class because they are private. Changing it to protected makes it possible, while not affecting anything else.

Change private properties to protected in compiler

---

src/Compiler.php

Updated version of PR #590 without adding a sourceName property
(test checked and PSR2 ok)

Improve error messages

---

src/Block.php
src/Compiler.php
src/Parser.php
tests/inputs/at_root.scss
tests/inputs/interpolation.scss
tests/outputs/at_root.css
tests/outputs/interpolation.css
tests/outputs_numbered/at_root.css
tests/outputs_numbered/interpolation.css

I fully reworked the proposal for PR #627 as it had no test case and it appears that the patch was causing `@at-root` directive to fail in some already existing tests
* Adding test-case for the interpolation `&{#}` selector without and with at-root parent
* keeping the PHPUnit version
* spliting the patch in several commits to make it more understandable
Tests are OK and PSR2 compliant.
I'm sorry i was not able to keep the credits to @kingyond as I really had do break the full patch in parts to understand how it was (not fully) working before being able to build this new patch, but the original commit really helped me!

Pr/leafo/627 : Add interpolation support selector

---

src/Compiler.php
src/SourceMap/SourceMapGenerator.php

Adding a rooted URI (starting with '/') as a the map filename can result in a double slash within the resulting `SourceMapGenerator` full path calculations which then results in unstable maps. I have added an additional check to avoid double slashes.
For example:
```php
$scss->setSourceMap(Compiler::SOURCE_MAP_INLINE);
$scss->setSourceMapOptions([
'sourceMapFilename' => '/example/path/to/css.scss',
'sourceMapBasepath' => '/var/www/vhosts/path-to-host',
'sourceRoot' => '/'
]);
$source = $scss->compile($this->source, '/example/path/to/css.scss');
```
Can result in a full path of  `/var/www/vhosts/path-to-host//example/path/to/css.scss`. 
Since all of our URIs are rooted in this way I have added an additional check to avoid double slashes. Hopefully this might help someone else with similar …

 Fix rooted SCSS URIs normalised incorrectly with double slashes

---

src/Compiler.php
tests/inputs/extending_compound_selector.scss
tests/outputs/extending_compound_selector.css
tests/outputs_numbered/extending_compound_selector.css

Fix for issue https://github.com/leafo/scssphp/issues/634
Compiler was duplicating selectors, resulting in ".foo.bar.bar.bar.bar" that ended up failing at comparison, so compiler assumed it was new selector. Whole thing ended up in infinite loop.
Added code that prevents duplicates and a test case.
Output matches Ruby version, except that Ruby additionally shows a deprecation notice: 
```
DEPRECATION WARNING on line 18 of test.scss:
Extending a compound selector, .bar:before, is deprecated and will not be supported in a future release.
Consider "@extend .bar, :before" instead.
See http://bit.ly/ExtendCompound for details.
```

Avoid infinitely duplicating parts when extending selector

---

src/Compiler.php
src/Parser.php
tests/inputs/values.scss
tests/outputs/values.css
tests/outputs_numbered/values.css

unit test case, parser and compiler fix to allow to assign self `&` or `#{&}` to a variable

Fix for #620

---

src/Version.php

I propose to tag this curent state as a v0.8.0 as there has been a lot of improvements and fixes (and it now includes BS4 & Foundation compilation in test cases)
Then you can increment the master branch to v0.8.1 for further developments

Version 0.8.0 

---

src/Compiler.php
src/Parser.php

Moiving `commentSeen` property from `Compiler` to `Parser` as it used only in the `Parser`.
Fixes: #661

Moving `commentsSeen` property

---

composer.json

Php8 is alreay in the works and since this lib is not yet known to be compatible with it we should explicitly define that

define a upper bound for the php version requirement

---

src/Compiler.php

Fix #432: infinite recursion in nested @include/@content pattern due to a mistaken env picking
+ improve the debugging capabilities by having a full calling stack and throwing an error in case of the stack being larger than a thresold  - which has good chance to be a clue of infinite recursion.
(but the compilation of Foundation needs to get a stack length thresold of 25000, which is telling something about the framework complexity I guess)

Fix Issue/leafo/432

---

src/Formatter/Compressed.php
src/Formatter/Crunched.php

As relationshop operators in selectors are recombined in the compiler itself, the space around coming from the general gluing rule for selector part, it seems hard to break everything to make this buble up until the Formatter.
But I think a simple str_replace() in the Formatter is safe here and get the improvement at low cost.

Fix proposal for #598

---

src/Parser.php

2nd part of trying to fix #368:
Parser improvement to parse the content of :not() :has() :where() :is() itself as subselector - supporting all the selector syntax
At the moment the subselector is re-flatten after the parsing because the compiler not know how to deal with nested selector structure (this can be a future improvement in the compiler)

Parser improvement on :not(...) and others

---

src/Parser.php
tests/inputs/values.scss
tests/outputs/values.css
tests/outputs_numbered/values.css

Fix #507 and support all documented syntax on https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

Fix support for Unicode range syntax

---

src/Compiler.php
src/Parser.php
tests/inputs/comments.scss
tests/outputs/comments.css
tests/outputs_numbered/comments.css

Interpolation in comments

---

src/Compiler.php
tests/inputs/selector_functions.scss
tests/outputs/selector_functions.css
tests/outputs_numbered/selector_functions.css

Only `selector-unify()` is missing in the #310 list, but this is not the easiest as the compiler have not yet any internal function doing this job.
I pushed the PR so you can have a look, but I propose waiting it's complete to merge it.
The spec/test cases are taken from https://sass-lang.com/documentation/functions/selector with sometimes some addition for border cases

Selector functions implementation

---

README.md

Just a last PR here :)
Could be nice to display the archive information on the Readme, as it is more visible, but let you decide if it's acceptable or a bit too much

Archive information on the readme
