src/Compiler.php, tests/inputs/builtins.scss, tests/outputs/builtins.css
I've implemented the string functions added in SASS 3.3:
#191
=> 3.3 string functions

scss.inc.php, src/Compiler.php, src/Exception/CompilerException.php, src/Exception/ParseException.php, src/Parser.php
Replace `\Exceptions` with pretty ones
=> refactor exceptions

src/Compiler.php
Add feature to ignore scss errors and improve exception classes.
I'm ready to improve this PR if this features make sense.
=> ignore errors

src/Compiler.php, tests/inputs/nested_mixins.scss, tests/outputs/nested_mixins.css, tests/outputs_numbered/nested_mixins.css
This should resolve (or help resolve) #449, #446.
=> Resolve function arguments using mixin content scope

src/Compiler.php, tests/inputs/extends.scss, tests/inputs/extends_nesting.scss, tests/inputs/nested_mixins.scss, tests/outputs/extends.css, tests/outputs/extends_nesting.css, tests/outputs/nested_mixins.css, tests/outputs_numbered/extends.css, tests/outputs_numbered/extends_nesting.css, tests/outputs_numbered/nested_mixins.css
Direct relationships must be merged when extending. Note that this patch is based off the two other pull requests. #453 #454
=> Merge shared direct relationship when extending

src/Compiler.php, tests/inputs/extends.scss, tests/inputs/extends_nesting.scss, tests/inputs/nested_mixins.scss, tests/outputs/extends.css, tests/outputs/extends_nesting.css, tests/outputs/nested_mixins.css, tests/outputs_numbered/extends.css, tests/outputs_numbered/extends_nesting.css, tests/outputs_numbered/nested_mixins.css
In short, the following should is not valid:
```
input.btn {
color: blue;
}
div {
@extend .btn
}
```
See test case for more information.
Note: this is rebase on the other issues I worked on.
=> Do not extend decorated tags with another tag

src/SourceMap/SourceMapGenerator.php
Fix for Issue #546 where source map generation no longer works
=> Fix/restore working source map generation in 0.7.3

src/Compiler.php
=> fixed #570 

src/Compiler.php, src/Compiler/Environment.php
Updated version of https://github.com/leafo/scssphp/pull/414 :
* test checked
* PSR2 fixed
=> Fix handling for font shorthand syntax

composer.json, src/Compiler.php, tests/FrameworkTest.php, tests/inputs/nested_mixins.scss, tests/outputs/at_root.css, tests/outputs/nested_mixins.css, tests/outputs_numbered/at_root.css, tests/outputs_numbered/nested_mixins.css
This is an update of https://github.com/leafo/scssphp/pull/462 which is outdated
Sorry for @xNok, I was not able to cherry-pick and keep you as the author because the source repo doesnt exists any more.
=> Adding test for BS4 and Foundation 6 frameworks

src/Compiler.php
Just a little fix to get the tests fully working
=> Fix error execution in PHP 7.2

src/Compiler.php, tests/inputs/extends.scss, tests/outputs/extends.css, tests/outputs_numbered/extends.css
Fix #660, including test case and fix
=> Fix :not() in @extend 

tests/inputs/media.scss, tests/outputs/media.css, tests/outputs_numbered/media.css
which is no longer an issue and is already fixed
=> Test case for #517

src/Compiler.php
This is completing #669 which was not perfect and fixes now #511 and #423
=> @media evaluation scope

src/Compiler.php
Fix #409 - was almost fixed already by #672 but the final @media was not super clean and was missing a parenthesis.
Now fully good
=> Better slicing the interpolated @media expression

src/Version.php
Think taging a new version would not be bad :)
=> Version 0.8.1

scss.inc.php, src/Cache.php, src/Compiler.php, src/Parser.php
Update and improvement of #639
=> Cache system for parser and compiler

src/Compiler.php, tests/inputs/extending_compound_selector.scss, tests/inputs/extends.scss, tests/inputs/extends_nesting.scss, tests/outputs/extending_compound_selector.css, tests/outputs/extends.css, tests/outputs/extends_nesting.css, tests/outputs_numbered/extending_compound_selector.css, tests/outputs_numbered/extends.css, tests/outputs_numbered/extends_nesting.css
Fix #67 #567 as well as #544 with 2 additional tests and unchanged results for the existing tests
=> Fix several bugs on @extend

src/Compiler.php
you should revert [self] to & https://github.com/leafo/scssphp/issues/368
First part of solving #368
=> Before reparsing a selector that need a double pass, 

src/Compiler.php, tests/inputs/at_root.scss, tests/outputs/at_root.css, tests/outputs_numbered/at_root.css
and fix also #380 which was already fixed for the @import scoping part
=> Fix @at-root vars scope

src/Parser.php, tests/inputs/interpolation.scss, tests/outputs/interpolation.css, tests/outputs/values.css, tests/outputs_numbered/interpolation.css, tests/outputs_numbered/values.css
Fix #586 with some implication on content strings with this continuation mark
I think this is safe to merge but a double check would not be bad
=> backslash-newline in strings
